### ISSUE TITLE
"Await expression not allowed in formal parameter"

### ISSUE THREAD

**Issue by ooptimum** [buxlabs/amd-to-es6#118]
I'm getting this false error message in an unexpected place of the correct working code. I suppose it is directly related to [this issue](https://github.com/cherow/cherow/issues/237). You use an outdated affected version of the cherow library in your abstract-syntax-tree library, on which this project depends.

**Comment by emilos** [comment]
@ooptimum I've changed `cherow` to `meriyah` in the `abstract-syntax-tree` dependency. I've also released a new version of this lib `v0.15.0` that uses the latest `abstract-syntax-tree`. Would you mind checking if this solves your problem? A PR with a test case would be highly appreciated to avoid potential regressions. Thanks!

**Comment by emilos** [comment]
We're using an updated version of `meriyah` now, so this issue should be resolved. Please reopen if that's not the case.
