### ISSUE TITLE
Plan for adding sourcemap support?

### ISSUE THREAD

**Issue by rafabernad** [buxlabs/amd-to-es6#15]
Hi, I was wondering if you were planning about adding source map support for this conversion utility

**Comment by emilos** [comment]
Hey @rafabernad, I did not, but only due to the limited time frame I had a couple of months ago. I'll happily accept a PR / work on this together if you want to give it a go 👍

**Comment by emilos** [comment]
@rafabernad thanks again! I published it as `v0.10.0`. I'll take care of moving it to the `ast` dep

**Comment by rafabernad** [comment]
You're welcome! Glad to help.

________________________________
