### ISSUE TITLE
Use mkdirp or equivalent in recursive mode to create the directories?

### ISSUE THREAD

**Issue by jfrux** [buxlabs/amd-to-es6#64]
When I add -r it is erroring on creating directories since they don't exist...?

**Comment by emilos** [comment]
hey @joshuairl :) thanks for the report, I'll have a look. How did the full command look like? That would help to find the issue.

**Comment by emilos** [comment]
@joshuairl should be fixed in https://github.com/buxlabs/amd-to-es6/commit/e8e9ea858f6e2559b2b1d5d19ccb3a2638c268fb, released as `0.9.2`. Thanks for the report :)
