### ISSUE TITLE
neweset version lacks node 4 support

### ISSUE THREAD

**Issue by kellyselden** [buxlabs/amd-to-es6#85]
Not sure if that was intentional or not. https://github.com/piuccio/rollup-plugin-amd/issues/14#issuecomment-360527074

**Comment by emilos** [comment]
I didn't consider it, and marked it here:

```js
"engines": {
  "node": ">=8.9.1"
},
```

but it wouldn't hurt I guess :) I'll fix that

**Comment by emilos** [comment]
@kellyselden this has been released as `0.12.1` here https://github.com/buxlabs/amd-to-es6/commit/711b68b85ae85ca7553b07e4c8111c9669b3f498 thanks!

**Comment by kellyselden** [comment]
Can you do this to @buxlabs/utils too please?
