### ISSUE TITLE
Preserve line breaks

### ISSUE THREAD

**Issue by malladi-s** [buxlabs/amd-to-es6#87]
Line breaks are currently not being preserved. If the input is 

```
define([], function() {
    var a = {
        a: 97
    };

    var b = {
        b: 98
    };
});

```

output 

```
var a = { a: 97 };
var b = { b: 98 };
```

Would it be possible to add another option to preserve line breaks?

**Comment by emilos** [comment]
hey @invictusmaneo if `prettier` supports that then probably yes, did you try to use the `beautify` option? That might help a little bit. It passes the options down to that lib

Other option would be to do some postprocessing on your own, e.g. with `eslint --fix`, `prettier` or any other tool that you'd like. Whatever seems simpler for you :). Please feel free to add a PR with a readme update if this helps
